# Generated by Django 5.0.1 on 2024-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'stadium',
                'verbose_name_plural': 'stadiums',
                'unique_together': {('name', 'location')},
            },
        ),
    ]
