# Generated by Django 5.0.1 on 2024-01-26 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stadiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_side', models.CharField(max_length=50)),
                ('away_side', models.CharField(max_length=50)),
                ('match_day', models.DateField()),
                ('match_time', models.TimeField()),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stadiums.stadium')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
                'unique_together': {('stadium', 'match_day', 'match_time')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.IntegerField()),
                ('is_reserved', models.BooleanField(blank=True, default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matches.match')),
            ],
            options={
                'verbose_name': 'seat',
                'verbose_name_plural': 'seats',
                'unique_together': {('match', 'seat_number')},
            },
        ),
    ]
